"""
Graph Provider Protocol

Defines the common interface for test graph database providers.
Both Neo4j and ArangoDB implementations satisfy this protocol.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Iterable, List, Optional, Protocol, Tuple

from app.models.entities import AppUserGroup, Record, RecordGroup, User

logger = logging.getLogger("test-graph-provider")


class GraphProviderProtocol(Protocol):
    """
    Protocol defining the test helper interface for graph database providers.

    Both TestNeo4jProvider and TestArangoHTTPProvider implement this protocol,
    allowing tests to work with either database transparently.
    """
    
    async def connect(self) -> bool: ...
    async def disconnect(self) -> bool: ...
    
    # Count methods
    async def count_records(self, connector_id: str) -> int: ...
    async def count_record_groups(self, connector_id: str) -> int: ...
    async def count_record_group_edges(self, connector_id: str) -> int: ...
    async def count_group_hierarchy_edges(self, connector_id: str) -> int: ...
    async def count_parent_child_edges(self, connector_id: str) -> int: ...
    async def count_permission_edges(self, connector_id: str) -> int: ...
    async def count_app_record_group_edges(self, connector_id: str) -> int: ...
    async def count_any_nodes_with_connector_id(self, connector_id: str) -> int: ...
    
    # Fetch methods
    async def fetch_record_paths(self, connector_id: str, limit: int = 200) -> List[Tuple[Optional[str], Optional[str]]]: ...
    async def fetch_record_names(self, connector_id: str) -> List[str]: ...
    async def get_record_by_name(self, connector_id: str, name: str) -> Optional[Dict[str, Any]]: ...
    async def get_record_parent_group(self, connector_id: str, record_name: str) -> Optional[str]: ...
    
    # Check methods
    async def record_path_or_name_contains(self, connector_id: str, substring: str) -> bool: ...
    async def record_name_path_contains(self, connector_id: str, record_name: str, path_substring: str) -> bool: ...
    async def record_paths_or_names_contain(self, connector_id: str, substrings: Iterable[str]) -> bool: ...
    
    # Assertion methods
    async def assert_min_records(self, connector_id: str, expected_min: int) -> None: ...
    async def assert_record_groups_and_edges(self, connector_id: str, min_groups: int | None = None, min_record_edges: int | None = None) -> None: ...
    async def assert_no_orphan_records(self, connector_id: str, max_orphans: int = 1) -> None: ...
    async def assert_app_record_group_edges(self, connector_id: str, min_edges: int = 1) -> None: ...
    async def assert_record_paths_or_names_contain(self, connector_id: str, expected_substrings: Iterable[str]) -> None: ...
    async def assert_record_not_exists(self, connector_id: str, name: str) -> None: ...
    async def assert_connector_graph_fully_cleaned(self, connector_id: str, timeout: int = 180) -> None: ...
    async def assert_all_records_cleaned(self, connector_id: str, timeout: int = 180) -> None: ...
    async def assert_record_count_unchanged(self, connector_id: str, expected: int, tolerance: int = 0) -> None: ...
    async def assert_record_paths_contain(self, connector_id: str, expected_substrings: Iterable[str]) -> None: ...
    async def assert_record_names_contain(self, connector_id: str, expected_names: Iterable[str]) -> None: ...
    
    # Summary methods
    async def graph_summary(self, connector_id: str) -> Dict[str, int]: ...
    async def get_record_parent_path(self, connector_id: str, record_name: str) -> Optional[str]: ...
    async def record_file_path_for_name(self, connector_id: str, record_name: str) -> Optional[str]: ...
    
    # User/Org methods (e2e tests)
    async def graph_find_user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def graph_find_user_by_user_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def graph_find_org(self, org_id: str) -> dict[str, Any] | None: ...
    async def graph_org_exists(self, org_id: str) -> bool: ...
    
    # Entity lookup methods (for assertions framework)
    async def get_record_by_external_id(self, connector_id: str, external_record_id: str) -> Optional[Record]: ...
    async def get_record_group_by_external_id(self, connector_id: str, external_id: str) -> Optional[RecordGroup]: ...
    async def get_user_by_source_id(self, source_user_id: str, connector_id: str) -> Optional[User]: ...
    async def get_user_group_by_external_id(self, connector_id: str, external_id: str) -> Optional[AppUserGroup]: ...
    
    # Relationship methods
    async def count_group_members(self, connector_id: str, external_group_id: str) -> int: ...
    async def record_inherits_permissions(self, connector_id: str, external_record_id: str) -> bool: ...
    
    # Bulk fetch methods
    async def fetch_records_by_type(self, connector_id: str, record_type: str) -> List[Dict[str, Any]]: ...
