{{- if .Values.secretManagement.externalSecrets.enabled }}
apiVersion: external-secrets.io/{{ .Values.secretManagement.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "pipeshub-ai.fullname" . }}-externalsecret
  labels:
    {{- include "pipeshub-ai.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretManagement.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretManagement.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.secretManagement.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "pipeshub-ai.secretName" . }}
    creationPolicy: Owner
  data:
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.secretKey }}
    - secretKey: secret-key
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.mongodbUsername }}
    - secretKey: mongodb-username
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.mongodbPassword }}
    - secretKey: mongodb-password
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.redisPassword }}
    - secretKey: redis-password
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.neo4jPassword }}
    - secretKey: neo4j-password
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.arangoPassword }}
    - secretKey: arango-password
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.secretManagement.externalSecrets.remoteRefs.qdrantApiKey }}
    - secretKey: qdrant-api-key
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
{{- end }}
