apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeshub-ai.fullname" . }}
  labels:
    {{- include "pipeshub-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8091
      targetPort: main
      protocol: TCP
      name: main
    - port: 8088
      targetPort: connector
      protocol: TCP
      name: connector
    - port: 3001
      targetPort: backend
      protocol: TCP
      name: backend
    - port: 8000
      targetPort: query
      protocol: TCP
      name: query
    - port: 8081
      targetPort: indexing
      protocol: TCP
      name: indexing
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "pipeshub-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main
