"""Capture the real connector-page query once, then replay variants of it.

The baseline is generated BY THE PROVIDER, never hand-copied: `capture()`
monkeypatches `Neo4jClient.execute_query` and calls
`get_knowledge_hub_connector_page_v3` for real. That is what stops the arms
drifting from shipped code the way `docs/kh-v3/*.cypher` already did.

Each arm is a text transform over that baseline. Every transform asserts it
actually matched -- a silently-inapplicable edit would otherwise produce a
"1.0x, no effect" result that looks like a finding.

Two rules enforced here:
  * a PROFILEd run is never a timing sample (profiling forces materialisation);
  * an arm whose returned page differs from the control is reported as BROKEN,
    never as a speedup.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import statistics
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

sys.path.insert(0, str(Path(__file__).resolve().parent))

from harness import Harness  # noqa: E402

Transform = Callable[[str], str]


def sub(old: str, new: str, *, count: int = 1, label: str = "") -> Transform:
    """A text replacement that fails loudly when it does not apply."""

    def apply(query: str) -> str:
        if query.count(old) < count:
            raise AssertionError(
                f"transform {label!r} did not match (wanted {count}, "
                f"found {query.count(old)}): {old[:90]!r}"
            )
        return query.replace(old, new, count)

    return apply


def chain(*transforms: Transform) -> Transform:
    def apply(query: str) -> str:
        for t in transforms:
            query = t(query)
        return query

    return apply


# --------------------------------------------------------------------------
# Arm definitions. "breaking" arms are diagnostic only and are expected to
# change the result set; "preserving" arms must not.
# --------------------------------------------------------------------------

HOP_INHERIT = "EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }"
SEED_INHERIT = "EXISTS { (cc)-[:INHERIT_PERMISSIONS]->(pc) }"

LISTING_UNWIND = """        UNWIND allIds AS vid
        MATCH (node:Record|RecordGroup {id: vid})"""

LISTING_DEDUP = """        UNWIND allIds AS rawVid
        WITH app, collect(DISTINCT rawVid) AS dedupIds
        UNWIND dedupIds AS vid
        MATCH (node:Record|RecordGroup {id: vid})"""

HIDDEN_GUARD = """          AND NOT EXISTS {
              MATCH (hid:RecordGroup)-[:NODE_RELATION*1..20]->(sd)
              WHERE coalesce(hid.hideChildren, false)
          }"""

NOT_IN_TESTS = """          AND NOT sd.id IN regionA
          AND NOT sd.id IN belowDeclared
          AND NOT sd.id IN declaredScope"""


def _arm_kill(var: str, start_marker: str, end_marker: str, label: str) -> Transform:
    """Replace a whole scope arm with an empty list for its output variable."""

    def apply(query: str) -> str:
        i = query.find(start_marker)
        if i < 0:
            raise AssertionError(f"{label}: start marker not found")
        j = query.find(end_marker, i)
        if j < 0:
            raise AssertionError(f"{label}: end marker not found")
        return query[:i] + end_marker + query[j + len(end_marker):]

    return apply


def block(start_marker: str, end_marker: str, replacement: str,
          *, label: str) -> Transform:
    """Replace a whole block, from the line holding `start_marker` through the
    line holding `end_marker`, with `replacement`.

    Arm kills keep the arm's output variable in scope (bound to `[]`) so every
    downstream clause still parses and still pays its own cost.
    """

    def apply(query: str) -> str:
        lines = query.splitlines()
        starts = [i for i, ln in enumerate(lines) if start_marker in ln]
        if not starts:
            raise AssertionError(f"{label}: start marker not found: {start_marker!r}")
        i = starts[0]
        ends = [j for j, ln in enumerate(lines) if j >= i and end_marker in ln]
        if not ends:
            raise AssertionError(f"{label}: end marker not found: {end_marker!r}")
        j = ends[0]
        return chr(10).join(lines[:i] + [replacement] + lines[j + 1:])

    return apply


ARMS: dict[str, tuple[str, Transform]] = {}


def register(name: str, kind: str, transform: Transform) -> None:
    ARMS[name] = (kind, transform)


register("control", "preserving", lambda q: q)

# --- Tier 2: semantics-preserving candidates -------------------------------
register("dedup_allids", "preserving",
         sub(LISTING_UNWIND, LISTING_DEDUP, label="dedup_allids"))

register("planner_dp", "preserving", lambda q: "CYPHER planner=dp\n" + q)
register("replan_force", "preserving", lambda q: "CYPHER replan=force\n" + q)

# --- Tier 1: diagnostic ablations ------------------------------------------
# count=1: the shipped hop now names the probe ONCE. These arms wanted it twice
# and skipped loudly after the factoring landed -- which is the point of making
# every transform assert. Their pre-factoring numbers (1.22x / 1.99x) measured a
# saving that the shipped change has since banked.
register("no_inherit_probe_true", "breaking",
         chain(sub(HOP_INHERIT, "true", count=1, label="hop_inherit_true"),
               sub(SEED_INHERIT, "true", label="seed_inherit_true")))
register("no_inherit_probe_false", "breaking",
         chain(sub(HOP_INHERIT, "false", count=1, label="hop_inherit_false"),
               sub(SEED_INHERIT, "false", label="seed_inherit_false")))
register("no_hidden_guard", "breaking",
         sub(HIDDEN_GUARD, "", label="no_hidden_guard"))
register("no_notin_tests", "breaking",
         sub(NOT_IN_TESTS, "", label="no_notin_tests"))
register("depth13", "breaking",
         lambda q: q.replace("{1,50}", "{1,13}"))
register("depth5", "breaking",
         lambda q: q.replace("{1,50}", "{1,5}"))
register("depth1", "breaking",
         lambda q: q.replace("{1,50}", "{1,1}"))
register("parent_child_only", "breaking",
         lambda q: q.replace("-[:NODE_RELATION]->", "-[khr:NODE_RELATION]->")
         .replace("WHERE NOT coalesce(ca.isDeleted, false)",
                  "WHERE khr.relationshipType = 'PARENT_CHILD' "
                  "AND NOT coalesce(ca.isDeleted, false)"))

# --- Tier 1: kill one scope arm at a time (seven arms, not six) -------------
register("kill_A1_regionA", "breaking", block(
    "OPTIONAL MATCH (app)", "collect(DISTINCT na.id) AS regionA",
    "        WITH app, appOpensEverything, [] AS regionA", label="A1"))
register("kill_A2_declared", "breaking", block(
    "OPTIONAL MATCH (dg:RecordGroup)", "collect(DISTINCT dg.id) AS declaredIds",
    "        WITH app, regionA, [] AS declaredIds", label="A2"))
register("kill_A3_nested", "breaking", block(
    "OPTIONAL MATCH (db:RecordGroup)", "collect(DISTINCT nb.id) AS nestedIds",
    "        WITH app, regionA, declaredIds, [] AS nestedIds", label="A3"))
register("kill_A4_belowDeclared", "breaking", block(
    "OPTIONAL MATCH (mb:Record)", "collect(DISTINCT mb.id) AS belowDeclared",
    "        WITH app, regionA, declaredScope, [] AS belowDeclared", label="A4"))
register("kill_A5_seeds", "breaking", block(
    "OPTIONAL MATCH (sd:Record|RecordGroup)", "collect(DISTINCT sd.id) AS seedIds",
    "        WITH app, regionA, declaredScope, belowDeclared, [] AS seedIds",
    label="A5"))
register("kill_A6_belowSeeds", "breaking", block(
    "OPTIONAL MATCH (sc:Record|RecordGroup)", "collect(DISTINCT nc.id) AS belowSeeds",
    "        WITH app, regionA, declaredScope, belowDeclared, seedIds,"
    " [] AS belowSeeds", label="A6"))
register("kill_A7_collections", "breaking", block(
    "OPTIONAL MATCH (cl:Record)", "collect(DISTINCT cl.id) AS collectionIds",
    "        WITH app, regionA, declaredScope, belowDeclared, seedIds, belowSeeds,"
    " [] AS collectionIds", label="A7"))

# --- Tier 1: listing / tail / enrich ---------------------------------------
register("no_enrich", "breaking", block(
    "UNWIND range(0, size(page) - 1) AS idx", "head(collect(nGroup)) AS nGroup",
    "        RETURN page AS rows, total, nRecord, nFolder, nGroup", label="no_enrich"))
register("no_counts", "breaking", sub(
    """WITH ordered, size(ordered) AS total,
             size([n IN ordered WHERE n.nodeType = 'record' | 1]) AS nRecord,
             size([n IN ordered WHERE n.nodeType = 'folder' | 1]) AS nFolder,
             size([n IN ordered WHERE n.nodeType = 'recordGroup' | 1]) AS nGroup""",
    "WITH ordered, size(ordered) AS total, 0 AS nRecord, 0 AS nFolder, 0 AS nGroup",
    label="no_counts"))
register("no_sort", "breaking", sub(
    "ORDER BY nullRank ASC, sortKey ASC, node.id ASC", "", label="no_sort"))


SLIM_MIN = (
    "        WITH { id: node.id,"
    " name: coalesce(node.name, node.recordName, node.groupName),"
    " nodeType: CASE WHEN node:RecordGroup THEN 'recordGroup'"
    " WHEN node.mimeType IN ['application/vnd.folder',"
    " 'application/vnd.google-apps.folder']"
    " OR toUpper(coalesce(node.recordType, '')) = 'FOLDER'"
    " THEN 'folder' ELSE 'record' END,"
    " isPlaceholder: coalesce(node.isPlaceholder, false) } AS node"
)


def slim_min(query: str) -> str:
    """Build only the slim fields anything downstream actually reads.

    `{tail}` collects id/nodeType/sortKey/nullRank, the sort reads `name`, and
    `{enrich}` re-MATCHes the page rows and rebuilds the full projection from
    the real node. The other nine fields exist only for `filter_clause`, so with
    no active filters they are computed for every visible node and discarded.
    """
    lines = query.splitlines()
    hits = [i for i, ln in enumerate(lines)
            if ln.startswith("        WITH { id: node.id,")]
    if not hits:
        raise AssertionError("slim_min: slim projection line not found")
    lines[hits[0]] = SLIM_MIN
    return chr(10).join(lines)


HOP_ORIGINAL = """AND (appOpensEverything
                OR (coalesce(ca.accessRule, 'OPEN') = 'RESTRICTED'
                    AND EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }
                    AND ca.id IN $grantedIds)
                OR (coalesce(ca.accessRule, 'OPEN') IN ['STRICT', 'OPEN']
                    AND (EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }
                      OR ca.id IN $grantedIds)))"""

# Same predicate, with the inheritance probe named once instead of twice.
# With R = accessRule, I = the probe, G = the grant test, the original is
#   (R='RESTRICTED' AND I AND G) OR (R IN ['STRICT','OPEN'] AND (I OR G))
# and this is
#   (I AND (R IN ['STRICT','OPEN'] OR (R='RESTRICTED' AND G)))
#   OR (R IN ['STRICT','OPEN'] AND G)
# which agrees on all three declared values AND still yields false for an
# undeclared one -- the fail-open trap decision 77 records for the obvious
# three-conjunct compaction.
HOP_FACTORED = """AND (appOpensEverything
                OR (EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }
                    AND (coalesce(ca.accessRule, 'OPEN') IN ['STRICT', 'OPEN']
                      OR (coalesce(ca.accessRule, 'OPEN') = 'RESTRICTED'
                          AND ca.id IN $grantedIds)))
                OR (coalesce(ca.accessRule, 'OPEN') IN ['STRICT', 'OPEN']
                    AND ca.id IN $grantedIds))"""

# The per-hop permission rule, ablated two ways. Both are diagnostic only.
#
# `no_accessrule_branches` keeps inheritance and the grant test but drops the
# STRICT / OPEN / RESTRICTED branching -- i.e. "is this node's flag checked at
# all", which is the cost of the rule's own logic rather than of its probes.
# `no_rule_at_all` removes the whole permission predicate from the hop, leaving
# only the structural guards, and so is the floor for what the walk can cost.
RULE_FACTORED = """AND (appOpensEverything
                OR (EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }
                    AND (coalesce(ca.accessRule, 'OPEN') IN ['STRICT', 'OPEN']
                      OR (coalesce(ca.accessRule, 'OPEN') = 'RESTRICTED'
                          AND ca.id IN $grantedIds)))
                OR (coalesce(ca.accessRule, 'OPEN') IN ['STRICT', 'OPEN']
                    AND ca.id IN $grantedIds))"""

RULE_NO_BRANCHES = """AND (appOpensEverything
                OR EXISTS { (ca)-[:INHERIT_PERMISSIONS]->(pa) }
                OR ca.id IN $grantedIds)"""

register("no_accessrule_branches", "breaking",
         sub(RULE_FACTORED, RULE_NO_BRANCHES, label="no_accessrule_branches"))
register("no_rule_at_all", "breaking",
         sub(RULE_FACTORED, "AND true", label="no_rule_at_all"))

register("hop_factored", "preserving",
         sub(HOP_ORIGINAL, HOP_FACTORED, label="hop_factored"))
register("dedup_slim_factored", "preserving", chain(
    sub(LISTING_UNWIND, LISTING_DEDUP, label="dedup"), slim_min,
    sub(HOP_ORIGINAL, HOP_FACTORED, label="hop_factored")))


ARM6_ORIGINAL = """        OPTIONAL MATCH (sc:Record|RecordGroup)
              ((pc)-[:NODE_RELATION]->(cc)
               WHERE NOT coalesce(cc.isDeleted, false)
                 AND NOT coalesce(pc.hideChildren, false)
                 AND coalesce(cc.accessRule, 'OPEN') = 'OPEN'
                 AND (EXISTS { (cc)-[:INHERIT_PERMISSIONS]->(pc) }
                   OR cc.id IN $grantedIds)
              ){1,50} (nc)
        WHERE sc.id IN seedIds
        WITH app, regionA, declaredScope, belowDeclared, seedIds,
             collect(DISTINCT nc.id) AS belowSeeds"""

# Anchor the seed walk on a seek rather than filtering `sc.id IN seedIds` after
# the pattern. If the planner applies that filter above the Repeat, the walk
# starts at every Record|RecordGroup in the store even when there are no seeds.
# `collect` over zero rows still returns one row holding [], so the empty-seeds
# case keeps its row -- which a bare UNWIND of [] would not.
ARM6_ANCHORED = """        CALL (seedIds) {
            UNWIND seedIds AS khSeedId
            MATCH (sc:Record|RecordGroup {id: khSeedId})
                  ((pc)-[:NODE_RELATION]->(cc)
                   WHERE NOT coalesce(cc.isDeleted, false)
                     AND NOT coalesce(pc.hideChildren, false)
                     AND coalesce(cc.accessRule, 'OPEN') = 'OPEN'
                     AND (EXISTS { (cc)-[:INHERIT_PERMISSIONS]->(pc) }
                       OR cc.id IN $grantedIds)
                  ){1,50} (nc)
            RETURN collect(DISTINCT nc.id) AS belowSeeds
        }
        WITH app, regionA, declaredScope, belowDeclared, seedIds, belowSeeds"""

register("anchor_belowseeds", "preserving",
         sub(ARM6_ORIGINAL, ARM6_ANCHORED, label="anchor_belowseeds"))
register("all_landed_plus_anchor", "preserving", chain(
    sub(ARM6_ORIGINAL, ARM6_ANCHORED, label="anchor_belowseeds")))


REDUNDANT_FILTER = (
    chr(10) + "        WHERE NOT coalesce(node.isPlaceholder, false)" + chr(10)
)

register("slim_min", "preserving", slim_min)
register("dedup_slim", "preserving", chain(
    sub(LISTING_UNWIND, LISTING_DEDUP, label="dedup"), slim_min))
register("dedup_slim_nofilter", "preserving", chain(
    sub(LISTING_UNWIND, LISTING_DEDUP, label="dedup"), slim_min,
    sub(REDUNDANT_FILTER, chr(10), label="drop_redundant_isplaceholder")))


SLIM_FULL = (
    "        WITH { id: node.id,"
    " name: coalesce(node.name, node.recordName, node.groupName),"
    " nodeType: CASE WHEN node:RecordGroup THEN 'recordGroup'"
    " WHEN node.mimeType IN ['application/vnd.folder',"
    " 'application/vnd.google-apps.folder']"
    " OR toUpper(coalesce(node.recordType, '')) = 'FOLDER'"
    " THEN 'folder' ELSE 'record' END,"
    " recordType: node.recordType,"
    " indexingStatus: node.indexingStatus,"
    " createdAt: coalesce(node.createdAtTimestamp, 0),"
    " updatedAt: coalesce(node.updatedAtTimestamp, 0),"
    " sizeInBytes: node.sizeInBytes,"
    " origin: coalesce(node.origin, CASE WHEN app.type = 'KB'"
    " THEN 'COLLECTION' ELSE 'CONNECTOR' END),"
    " connector: coalesce(node.connector, app.type),"
    " connectorId: coalesce(node.connectorId, app.id),"
    " isPlaceholder: coalesce(node.isPlaceholder, false),"
    " hasChildren: false } AS node"
)

DEDUP_NOW = """        UNWIND allIds AS rawVid
        WITH app, collect(DISTINCT rawVid) AS dedupedIds
        UNWIND dedupedIds AS vid"""
DEDUP_WAS = "        UNWIND allIds AS vid"


def to_legacy(query: str) -> tuple[str, list[str]]:
    """Rebuild the pre-optimization query from whatever the provider emits now.

    Both arms then come from the same live provider output, so this keeps
    working as the surrounding query evolves -- unlike a checked-in copy of the
    old Cypher, which is how `docs/kh-v3/*.cypher` drifted out of date.
    """
    applied: list[str] = []

    if DEDUP_NOW in query:
        query = query.replace(DEDUP_NOW, DEDUP_WAS, 1)
        applied.append("dedup")

    lines = query.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("        WITH { id: node.id,"):
            if line != SLIM_FULL:
                lines[i] = SLIM_FULL
                applied.append("slim")
            break
    query = chr(10).join(lines)

    if HOP_FACTORED in query:
        applied.append("hop x%d" % query.count(HOP_FACTORED))
        query = query.replace(HOP_FACTORED, HOP_ORIGINAL)

    return query, applied


def legacy_arm(query: str) -> str:
    rebuilt, applied = to_legacy(query)
    if not applied:
        raise AssertionError(
            "legacy: no revert applied -- the provider no longer emits the "
            "optimized form these transforms invert"
        )
    return rebuilt


register("legacy", "preserving", legacy_arm)

# The original (pre-optimization) query with the per-hop permission rule removed
# entirely -- i.e. "what would HEAD have cost if the rule were free". Needs its
# own transform because `no_rule_at_all` targets the FACTORED rule text, which
# only exists after the optimization landed.
register("legacy_no_rule", "breaking", chain(
    legacy_arm, sub(HOP_ORIGINAL, "AND true", label="legacy_no_rule")))


@dataclass
class ArmResult:
    name: str
    kind: str
    ok: bool
    wall_ms: list[float] = field(default_factory=list)
    digest: str = ""
    total: int | None = None
    error: str = ""
    db_hits: int | None = None

    @property
    def median_ms(self) -> float:
        return statistics.median(self.wall_ms) if self.wall_ms else float("nan")

    @property
    def min_ms(self) -> float:
        return min(self.wall_ms) if self.wall_ms else float("nan")


async def capture(harness: Harness, app_id: str, *, limit: int = 50,
                  include_total: bool = True) -> tuple[str, dict[str, Any]]:
    """Run the real provider method once, intercepting the query it builds."""
    from app.services.graph_db.neo4j.neo4j_client import Neo4jClient

    captured: dict[str, Any] = {}
    original = Neo4jClient.execute_query

    async def intercept(self, query, parameters=None, txn_id=None):  # noqa: ANN001
        if "$gatedAppIds" in query and "allIds" in query:
            captured["query"] = query
            captured["params"] = dict(parameters or {})
        return await original(self, query, parameters=parameters, txn_id=txn_id)

    Neo4jClient.execute_query = intercept
    try:
        access = await harness.access("capture")
        await harness.provider.get_knowledge_hub_connector_page_v3(
            app_id=app_id, org_id=harness.user["org_id"],
            grantee_ids=access["grantee_ids"], gated_app_ids=access["gated_app_ids"],
            granted_ids=access["by_connector"].get(app_id) or [],
            limit=limit, flatten=True, sort_field="name", sort_dir="ASC",
            include_total=include_total,
        )
    finally:
        Neo4jClient.execute_query = original

    if "query" not in captured:
        raise SystemExit(f"Did not capture a page query for app {app_id}")
    return captured["query"], captured["params"]


def digest_rows(payload: dict[str, Any]) -> str:
    rows = payload.get("rows") or []
    ids = [str(r.get("id")) for r in rows]
    return hashlib.sha256("\n".join(ids).encode("utf-8")).hexdigest()[:16]


async def run_once(harness: Harness, query: str, params: dict[str, Any]) -> tuple[float, dict]:
    t0 = time.perf_counter()
    rows = await harness.provider.client.execute_query(query, parameters=params)
    elapsed = (time.perf_counter() - t0) * 1000.0
    return elapsed, (rows[0] if rows else {})


async def profile_arm(harness: Harness, query: str, params: dict[str, Any]) -> dict:
    """PROFILE the query and return total db hits plus the top operators.

    Separate from timing on purpose: profiling adds counters and forces
    materialisation, so its milliseconds are not comparable to an unprofiled run.
    """
    from neo4j import AsyncGraphDatabase

    s = harness.settings
    driver = AsyncGraphDatabase.driver(s.uri, auth=(s.username, s.password))
    try:
        async with driver.session(database=s.database) as session:
            result = await session.run("PROFILE " + query, params)
            await result.data()
            summary = await result.consume()
    finally:
        await driver.close()

    ops: list[dict] = []

    def walk(node, depth=0, path="") -> None:
        args = node.get("args", {}) or {}
        here = path + "/" + node.get("operatorType", "?")
        ops.append({
            "op": node.get("operatorType"),
            "depth": depth,
            "path": here,
            "rows": node.get("rows"),
            "est_rows": args.get("EstimatedRows"),
            "db_hits": node.get("dbHits"),
            "memory": args.get("Memory"),
            "details": str(args.get("Details", ""))[:110],
        })
        for child in node.get("children", []) or []:
            walk(child, depth + 1, here)

    walk(summary.profile)
    return {
        "total_db_hits": sum(o["db_hits"] or 0 for o in ops),
        "available_ms": summary.result_available_after,
        "consumed_ms": summary.result_consumed_after,
        "ops": ops,
    }


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--email", required=True)
    parser.add_argument("--app-id", default=None,
                        help="connector to target; default = the slowest")
    parser.add_argument("--arms", default="control")
    parser.add_argument("--reps", type=int, default=7)
    parser.add_argument("--warmup", type=int, default=2)
    parser.add_argument("--profile", action="store_true")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    harness = Harness(log_level=logging.WARNING)
    await harness.connect(email=args.email)
    before = await harness.counts()

    app_id = args.app_id
    if app_id is None:
        record = await harness.run_global_flatten()
        app_id = max(record.connectors, key=lambda c: c.wall_ms).app_id
        print(f"slowest connector: {app_id}")

    base_query, params = await capture(harness, app_id)
    print(f"captured query: {len(base_query)} chars, "
          f"{len(params.get('grantedIds') or [])} granted ids")

    names = [n.strip() for n in args.arms.split(",") if n.strip()]
    if names == ["all"]:
        names = list(ARMS)

    queries: dict[str, str] = {}
    results: dict[str, ArmResult] = {}
    for name in names:
        kind, transform = ARMS[name]
        try:
            queries[name] = transform(base_query)
            results[name] = ArmResult(name=name, kind=kind, ok=True)
        except AssertionError as exc:
            results[name] = ArmResult(name=name, kind=kind, ok=False, error=str(exc))
            print(f"SKIP {name}: {exc}")

    live = [n for n in names if results[n].ok]

    # Warm-up is per arm: each distinct query text gets its own plan-cache entry,
    # and giving one arm a warm plan and another a cold one fabricates a speedup.
    for _ in range(args.warmup):
        for name in live:
            await run_once(harness, queries[name], params)

    # Interleaved, order rotated per rep, so drift hits every arm equally.
    for rep in range(args.reps):
        order = live[rep % len(live):] + live[:rep % len(live)]
        for name in order:
            elapsed, payload = await run_once(harness, queries[name], params)
            r = results[name]
            r.wall_ms.append(elapsed)
            r.digest = digest_rows(payload)
            r.total = payload.get("total")

    if args.profile:
        for name in live:
            prof = await profile_arm(harness, queries[name], params)
            results[name].db_hits = prof["total_db_hits"]
            if args.out:
                out = Path(args.out)
                out.mkdir(parents=True, exist_ok=True)
                (out / f"{name}.profile.json").write_text(
                    json.dumps(prof, indent=2), encoding="utf-8")

    after = await harness.counts()
    print(f"\ncorpus before={before} after={after}"
          f"{'  (CHANGED - results not comparable)' if before != after else ''}")

    control = results.get("control")
    print(f"\n{'arm':<24} {'kind':<11} {'median':>9} {'min':>9} {'x':>6} "
          f"{'db_hits':>10} {'total':>7}  identity")
    print("-" * 96)
    for name in names:
        r = results[name]
        if not r.ok:
            print(f"{name:<24} {r.kind:<11} {'SKIPPED':>9}  {r.error[:40]}")
            continue
        speed = (control.median_ms / r.median_ms) if control and r.median_ms else 0
        if control is None or name == "control":
            identity = "-"
        elif r.digest == control.digest and r.total == control.total:
            identity = "same"
        else:
            identity = "DIFFERENT" if r.kind == "breaking" else "BROKEN"
        hits = f"{r.db_hits:,}" if r.db_hits is not None else "-"
        print(f"{name:<24} {r.kind:<11} {r.median_ms:8.1f}ms {r.min_ms:8.1f}ms "
              f"{speed:5.2f}x {hits:>10} {str(r.total):>7}  {identity}")

    await harness.close()


if __name__ == "__main__":
    asyncio.run(main())
